help

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -13,27 +13,23 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-     # - uses: actions/checkout@v3
-     # - uses: actions/setup-node@v3
-     # with:
-     #   node-version: '18.10.0'
-     #   cache: 'npm'
-     # - run: npm install
+      - name: Check out code
+      uses: actions/checkout@v3
+
+      - name: Install packages
+      uses: actions/setup-node@v3
+      - run: npm install
+
       - name: Run test
       run: npm run test
-      # Если ошибка 
-    #  - name: Error
-     # if: failure()
-     # run: exit 1
+#      - name: Error
+#      if: failure()
+#      run: exit 1
 
-      # Запуск сборки
-   #   - name: Ng build
-   #   run: npm run build
+      - name: Ng build
+      run: npm run build
 
-      # Пока хватит
-      #
-      #  
-      #
-      #
-      #
-      #
+#      - name: Build Docker image
+
+
+#      - name: Email
