4

diff --git a/.github/workflows/github-actions.yml b/.github/workflows/github-actions.yml
--- a/.github/workflows/github-actions.yml
+++ b/.github/workflows/github-actions.yml
@@ -13,24 +13,24 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-node@v3
-      with:
-        node-version: '18.10.0'
-        cache: 'npm'
-      - run: npm install
+     # - uses: actions/checkout@v3
+     # - uses: actions/setup-node@v3
+     # with:
+     #   node-version: '18.10.0'
+     #   cache: 'npm'
+     # - run: npm install
 
       # Запуск тестов (если тесты не пройдены, остановить выполнение и отправить выполнение об ошибке)
       - name: Run test
       run: npm run test
       # Если ошибка 
-      - name: Error
-      if: failure()
-      run: exit 1
+    #  - name: Error
+     # if: failure()
+     # run: exit 1
 
       # Запуск сборки
-      - name: Ng build
-      run: npm run build
+   #   - name: Ng build
+   #   run: npm run build
 
       # Пока хватит
       #
